---
apiVersion: v1
kind: application
metadata:
  name: devtest.socket
  commType: http
spec:
  services:
    - serviceName: socket
      components:
        - componentName: socket
          imageType: docker
          imageName: marquies/socket
          httpPort: 10042
          interfaces:
            - interfaceName: socket-network
              interfaceType: network
              interfacePort: 5011
              scheme: tcp
              visiblity: external
              accessList:
                - app@client
            - interfaceName: context1
              interfaceType: http
              upstreamPath: /nickname
              visiblity: external
              accessList:
                - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default
